# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbc39bbf8b5aaf3fb3b6d94cfa63220bca2aa40510763ddc7c246bfb9bc0629062302786dab98c990b82f4196dbd51dceb34f12200dfb506daa69a0cc4720c57

test:
  secret_key_base: 27aaf99c2b6d33695f17151566eb2fb98368f43864cb7edf415de372cfafbe0b1045d77489dceeca52fff1480cb166bf990e617267d5b4a1b2f696fae88d352c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
